<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;
use App\Models\Permission;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class RemoveView extends Command
{
    protected $signature = 'remove:view {name}';
    protected $description = 'Surgically remove all generated files (including API layer) and database tables for a specific CRUD';

    public function handle()
    {
        $inputName = $this->argument('name');

        // We check both singular and plural to be sure
        $singularName = Str::studly(Str::singular($inputName));
        $pluralName = Str::studly(Str::plural($inputName));

        $pluralKebab = Str::kebab($pluralName);
        $pluralSnake = Str::snake($pluralName);
        $tableName = Str::snake($pluralName);

        $this->warn("🗑️  Removing CRUD ecosystem for $singularName/$pluralName...");

        // 0. Delete Domain Layer (Check both)
        foreach([$singularName, $pluralName] as $n) {
            $domainPath = app_path("Domain/$n");
            if (File::isDirectory($domainPath)) {
                File::deleteDirectory($domainPath);
                $this->info("✓ Deleted Domain Layer: app/Domain/$n");
            }
        }

        // 1. Delete Model (Check both)
        foreach([$singularName, $pluralName] as $n) {
            $modelPath = app_path("Models/$n.php");
            if (File::exists($modelPath)) {
                File::delete($modelPath);
                $this->info("✓ Deleted Model: app/Models/$n.php");
            }
        }

        // 2. Delete Livewire Components
        $livewirePath = app_path("Livewire/Admin/$pluralName");
        if (File::isDirectory($livewirePath)) {
            File::deleteDirectory($livewirePath);
            $this->info("✓ Deleted Livewire Components: app/Livewire/Admin/$pluralName");
        }

        // 3. Delete Views
        $viewPath = resource_path("views/livewire/admin/$pluralKebab");
        if (File::isDirectory($viewPath)) {
            File::deleteDirectory($viewPath);
            $this->info("✓ Deleted Views: resources/views/livewire/admin/$pluralKebab");
        }

        // 4. Delete Route Files
        $routeFile = base_path("routes/admin/$pluralKebab.php");
        if (File::exists($routeFile)) {
            File::delete($routeFile);
            $this->info("✓ Deleted Route File: routes/admin/$pluralKebab.php");
        }

        // 5. Realtime Layer Cleanup (generated by --api)
        foreach ([$singularName, $pluralName] as $n) {
            $eventPath = app_path("Events/{$n}Changed.php");
            if (File::exists($eventPath)) {
                File::delete($eventPath);
                $this->info("✓ Deleted Realtime Event: app/Events/{$n}Changed.php");
            }

            $observerPath = app_path("Observers/{$n}Observer.php");
            if (File::exists($observerPath)) {
                File::delete($observerPath);
                $this->info("✓ Deleted Observer: app/Observers/{$n}Observer.php");
            }
        }

        $channelsPath = base_path('routes/channels.php');
        if (File::exists($channelsPath)) {
            $channelsContent = File::get($channelsPath);
            $channelPattern = "/^.*Broadcast::channel\('mobile\.{$pluralKebab}'.*?\);\s*$/m";
            $cleanChannels = preg_replace($channelPattern, '', $channelsContent);
            if ($cleanChannels !== $channelsContent) {
                File::put($channelsPath, $cleanChannels);
                $this->info("✓ Removed Realtime channel: mobile.{$pluralKebab}");
            }
        }

        // Generated Flutter module. Never delete shared mobile-gateway/core files,
        // because they are shared by all scaffolded modules.
        $flutterModulePath = base_path("mobile-gateway/lib/modules/dashboard/" . Str::snake($singularName));
        if (File::isDirectory($flutterModulePath)) {
            File::deleteDirectory($flutterModulePath);
            $this->info("✓ Deleted Flutter module: mobile-gateway/lib/modules/dashboard/" . Str::snake($singularName));
            $this->unregisterFlutterModule($singularName);
        }

        // 6. API Layer Cleanup
        foreach([$singularName, $pluralName] as $n) {
            $apiController = app_path("Http/Controllers/Api/Mobile/{$n}Controller.php");
            if (File::exists($apiController)) {
                File::delete($apiController);
                $this->info("✓ Deleted API Controller: Mobile/$n" . "Controller");
            }

            $apiResource = app_path("Http/Resources/Mobile/{$n}Resource.php");
            if (File::exists($apiResource)) {
                File::delete($apiResource);
                $this->info("✓ Deleted API Resource: Mobile/$n" . "Resource");
            }

            $apiRequestDir = app_path("Http/Requests/Api/$n");
            if (File::isDirectory($apiRequestDir)) {
                File::deleteDirectory($apiRequestDir);
                $this->info("✓ Deleted API Requests: Http/Requests/Api/$n");
            }
        }

        // Remove API Route entry
        $apiRoutePath = base_path("routes/api.php");
        if (File::exists($apiRoutePath)) {
            $apiContent = File::get($apiRoutePath);
            $apiPattern = "/Route::apiResource\('$pluralKebab'.*?;/s";
            $newApiContent = preg_replace($apiPattern, '', $apiContent);
            File::put($apiRoutePath, $newApiContent);
            $this->info("✓ Cleaned up routes/api.php");
        }

        // 7. Delete Translation Files
        if (File::exists(lang_path())) {
            foreach (File::directories(lang_path()) as $dir) {
                $langFile = $dir . "/$pluralKebab.php";
                if (File::exists($langFile)) {
                    File::delete($langFile);
                    $this->info("✓ Deleted Translation File: " . basename($dir) . "/$pluralKebab.php");
                }
            }
        }

        // 7b. Delete Flutter Translation Files
        $snake = Str::snake($singularName);
        $flutterL10nPath = base_path("mobile-gateway/lib/l10n");
        if (File::exists($flutterL10nPath)) {
            foreach (['en', 'sq'] as $lang) {
                $file = "$flutterL10nPath/{$snake}_{$lang}.dart";
                if (File::exists($file)) {
                    File::delete($file);
                    $this->info("✓ Deleted Flutter Translation: l10n/{$snake}_{$lang}.dart");
                }
            }
            $locFile = "$flutterL10nPath/{$snake}_localization.dart";
            if (File::exists($locFile)) {
                File::delete($locFile);
                $this->info("✓ Deleted Flutter Localizer: l10n/{$snake}_localization.dart");
            }
        }

        // 8. Delete Migration & Drop Table
        if (Schema::hasTable($tableName)) {
            Schema::dropIfExists($tableName);
            $this->info("✓ Dropped Table: $tableName");
        }

        $migrations = File::files(database_path('migrations'));
        foreach ($migrations as $migration) {
            if (str_contains($migration->getFilename(), "create_{$tableName}_table")) {
                File::delete($migration->getPathname());
                $this->info("✓ Deleted Migration File: " . $migration->getFilename());
                DB::table('migrations')->where('migration', 'like', '%' . str_replace('.php', '', $migration->getFilename()) . '%')->delete();
            }
        }

        // 9. Remove Navigation Link
        $navPath = resource_path('views/components/layouts/app/navigation.blade.php');
        if (File::exists($navPath)) {
            $content = File::get($navPath);
            $pattern = "/@can\('view_{$pluralSnake}'\).*?@endcan/s";
            $newContent = preg_replace($pattern, '', $content);
            File::put($navPath, $newContent);
            $this->info("✓ Removed sidebar navigation link.");
        }

        // 10. Remove Permissions from DB
        Permission::where('module', $pluralName)
            ->orWhere('module', $singularName)
            ->orWhere('name', 'like', "%_{$pluralSnake}")
            ->delete();
        $this->info("✓ Removed permissions from database.");

        $this->info("✅ ALL components for $singularName have been surgically removed!");
    }

    protected function unregisterFlutterModule($name)
    {
        $registryPath = base_path('mobile-gateway/lib/modules/dashboard/presentation/pages/module_registry.dart');
        if (!File::exists($registryPath)) return;

        $content = File::get($registryPath);
        $snake = Str::snake($name);

        // Remove import
        $lines = explode("\n", $content);
        $lines = array_filter($lines, function($line) use ($snake) {
            $trimmed = trim($line);
            return !(str_starts_with($trimmed, "import") && str_contains($trimmed, "{$snake}_list_page.dart"));
        });

        $content = implode("\n", $lines);

        // Remove entry
        $entryPattern = "/ModuleEntry\(name:\s*['\"]{$name}['\"].*?\),\s*/s";
        $content = preg_replace($entryPattern, '', $content);

        // EXTRA CLEANUP: Remove any corrupted fragments that might be left behind (e.g. from failed edits)
        $corruptPattern = "/\s*permission:\s*['\"]view_" . Str::snake(Str::plural($name)) . "['\"]\),\s*/s";
        $content = preg_replace($corruptPattern, '', $content);

        File::put($registryPath, $content);
        $this->info("✓ Unregistered module from Flutter ModuleRegistry");
    }
}
